[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/buildpackapplifecycle"

[[constraint]]
  name = "code.cloudfoundry.org/cli"
  version = "=6.34.1"

[[constraint]]
  branch = "master"
  name = "github.com/sclevine/spec"
