[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/buildpackapplifecycle"

[[constraint]]
  name = "code.cloudfoundry.org/cli"
  version = "=6.35.2"

[[constraint]]
  branch = "master"
  name = "github.com/sclevine/spec"

[[constraint]]
  branch = "remote-layer"
  name = "github.com/google/go-containerregistry"
  source = "https://github.com/jonjohnsonjr/go-containerregistry"
