required = [
  "k8s.io/client-go/discovery",
]

[prune]
  unused-packages = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/buildpackapplifecycle"

[[constraint]]
  name = "code.cloudfoundry.org/cli"
  version = "=6.37.0"

[[constraint]]
  branch = "master"
  name = "github.com/sclevine/spec"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-containerregistry"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"
